name: slangary
description: "Mobile dictionary app for slang language mainly in English."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^14.7.2
  http: ^1.3.0
  path: ^1.9.0
  sqflite: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  uses-material-design: true
  fonts:
    - family: Sarabun
      fonts:
        # Thin
        - asset: assets/fonts/Sarabun/Sarabun-Thin.ttf
          weight: 100
        - asset: assets/fonts/Sarabun/Sarabun-ThinItalic.ttf
          weight: 100
          style: italic
        # Extra Light
        - asset: assets/fonts/Sarabun/Sarabun-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Sarabun/Sarabun-ExtraLightItalic.ttf
          weight: 200
          style: italic
        # Light
        - asset: assets/fonts/Sarabun/Sarabun-Light.ttf #used
          weight: 300
        - asset: assets/fonts/Sarabun/Sarabun-LightItalic.ttf
          weight: 300
          style: italic
        # Regular
        - asset: assets/fonts/Sarabun/Sarabun-Regular.ttf #used
        - asset: assets/fonts/Sarabun/Sarabun-Italic.ttf #used
          style: italic
        # Medium
        - asset: assets/fonts/Sarabun/Sarabun-Medium.ttf
          weight: 500
        - asset: assets/fonts/Sarabun/Sarabun-MediumItalic.ttf
          weight: 500
          style: italic
        # Semi Bold
        - asset: assets/fonts/Sarabun/Sarabun-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Sarabun/Sarabun-SemiBoldItalic.ttf
          weight: 600
          style: italic
        # Bold
        - asset: assets/fonts/Sarabun/Sarabun-Bold.ttf #used
          weight: 700
        - asset: assets/fonts/Sarabun/Sarabun-BoldItalic.ttf
          weight: 700
          style: italic
        # Extra Bold
        - asset: assets/fonts/Sarabun/Sarabun-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Sarabun/Sarabun-ExtraBoldItalic.ttf
          weight: 800
          style: italic